name: 'Deploy Chromatic'

on: [push, pull_request]

jobs:
  build:
    name: Deploy Storybook
    runs-on: ubuntu-latest

    steps:
      - uses: chromaui/action@v1
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          token: ${{ secrets.GH_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}